# Set build version format here instead of in the admin panel.
version: "{build}"
image: Visual Studio 2017

environment:
  IMAGE_NAME: gabiseabra/react-boilerplate:latest

init:
  - git config --global core.autocrlf input

install:
  - docker version

build_script:
  - docker build -t %IMAGE_NAME% .

test_script:
  - docker run  -d -p 80:80 -n project-test %IMAGE_NAME%
  - curl -v http://localhost:80
  - docker exec project-test npm run test
  - docker exec project-test npm run lint

deploy_script:
  - docker login -u %DOCKER_USER% -p %DOCKER_PASS%
  - docker push %IMAGE_NAME%
