image: docker:latest

services:
  - docker:dind

cache:
  untracked: true

variables:
  DOCKER_DRIVER: overlay
  DOCKER_USER: gitlab-ci-token
  DOCKER_PASS: $CI_JOB_TOKEN
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY

build:
  stage: build
  script:
    - docker build -t "$DOCKER_IMAGE:$CI_BUILD_REF" --pull .
    - docker push "$DOCKER_IMAGE:$CI_BUILD_REF"

test:
  stage: test
  script:
    - docker pull "$DOCKER_IMAGE:$CI_BUILD_REF"
    - docker run "$DOCKER_IMAGE:$CI_BUILD_REF" yarn run test

lint:
  stage: test
  script:
    - docker pull "$DOCKER_IMAGE:$CI_BUILD_REF"
    - docker run "$DOCKER_IMAGE:$CI_BUILD_REF" yarn run lint

release:
  stage: deploy
  script:
    - docker pull "$DOCKER_IMAGE:$CI_BUILD_REF"
    - docker build --cache-from "$DOCKER_IMAGE:$CI_BUILD_REF"
                   -t "$DOCKER_IMAGE:latest"
                   ./
    - docker push "$DOCKER_IMAGE:latest"
    - if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$DOCKER_IMAGE:latest" "$DOCKER_IMAGE:$CI_COMMIT_TAG"
        docker push "$DOCKER_IMAGE:$CI_COMMIT_TAG";
      fi
  only:
    - master
