image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_USER: gitlab-ci-token
  DOCKER_PASS: $CI_JOB_TOKEN
  DOCKER_REGISTRY: $CI_REGISTRY
  IMAGE_TEST: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  IMAGE_RELEASE: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - deploy

before_script:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY

build:
  stage: build
  script:
    - docker build -t $IMAGE_TEST --pull .
    - docker push $IMAGE_TEST

test:
  stage: test
  script:
    - docker pull $IMAGE_TEST
    - docker run $IMAGE_TEST yarn run test

lint:
  stage: test
  script:
    - docker pull $IMAGE_TEST
    - docker run $IMAGE_TEST yarn run lint

release:
  stage: deploy
  script:
    - docker pull $IMAGE_TEST
    - docker tag $IMAGE_TEST $IMAGE_RELEASE
    - docker push $IMAGE_RELEASE
  only:
    - master
