image: docker:latest

services:
  - docker:dind

cache:
  untracked: true

variables:
  DOCKER_DRIVER: overlay
  DOCKER_USER: gitlab-ci-token
  DOCKER_PASS: $CI_JOB_TOKEN
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  DOCKER_TEST_TAG: $CI_COMMIT_REF_NAME

stages:
  - build
  - test
  - deploy

build:
  stage: build
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY
  script:
    - docker build --build-arg NODE_ENV=development
                   --tag "$DOCKER_IMAGE:$DOCKER_TEST_TAG"
                   --pull
                   ./
    - docker push "$DOCKER_IMAGE:$DOCKER_TEST_TAG"

test:
  stage: test
  script:
    - docker pull "$DOCKER_IMAGE:$DOCKER_TEST_TAG"
    - docker run "$DOCKER_IMAGE:$DOCKER_TEST_TAG" npm run test

lint:
  stage: test
  script:
    - docker pull "$DOCKER_IMAGE:$DOCKER_TEST_TAG"
    - docker run "$DOCKER_IMAGE:$DOCKER_TEST_TAG" npm run lint

release:
  stage: deploy
  before_script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS $DOCKER_REGISTRY
  script:
    - docker pull "$DOCKER_IMAGE:$DOCKER_TEST_TAG"
    - docker build --cache-from "$DOCKER_IMAGE:$DOCKER_TEST_TAG"
                   --tag "$DOCKER_IMAGE:latest"
                   ./
    - docker push "$DOCKER_IMAGE:latest"
    - if [ -n "$CI_COMMIT_TAG" ]; then
        docker tag "$DOCKER_IMAGE:latest" "$DOCKER_IMAGE:$CI_COMMIT_TAG"
        docker push "$DOCKER_IMAGE:$CI_COMMIT_TAG";
      fi
  only:
    - master
