sudo: required

services:
  - docker

env:
  - IMAGE_NAME="gabiseabra/react-boilerplate:latest"

install:
  - docker version
  - docker build -t $IMAGE_NAME --pull .

script:
  - docker run -d -p 80:80 -n project-test $IMAGE_NAME
  - curl -v http://localhost:80
  - docker exec project-test npm run test
  - docker exec project-test npm run lint

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS";
    docker push $IMAGE_NAME;
    fi
