sudo: required

language: node_js

node_js: "7"

cache:
  yarn: true
  directories:
    - node_modules
    - public

services:
  - docker

env:
  - DOCKER_IMAGE="$TRAVIS_REPO_SLUG"

install:
  - yarn install --pure-lockfile
  - docker build --build-arg NODE_ENV=development
                 --tag "$DOCKER_IMAGE:dev"
                 --pull
                 ./

script:
  - docker run --name container-test -d "$DOCKER_IMAGE:dev"
  - docker exec container-test yarn run test
  - docker exec container-test yarn run lint

after_success:
  # Build production image
  - docker build --tag "$DOCKER_IMAGE:latest" ./
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
  # Push image tags
  - if [ "$TRAVIS_BRANCH" = "master" ]; then
      docker push "$DOCKER_IMAGE:latest";
    fi
  - if [ "$TRAVIS_TAG" ]; then
      docker tag "$DOCKER_IMAGE:latest" "$DOCKER_IMAGE:$TRAVIS_TAG";
      docker push "$DOCKER_IMAGE:$TRAVIS_TAG";
    fi
  - docker logout

before_deploy:
  # Copy build files from container
  - docker run --name container-latest -d "$DOCKER_IMAGE:latest"
  - rm -rf ./public
  - docker cp container-latest:app/public ./public
  # Build static files
  - yarn run build:static
  # Copy README to public folder
  - cp ./README.md ./public/README.md

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public/
  github_token: $GITHUB_TOKEN
  on:
    branch: master
